config/routes.rb
Rails.application.routes.draw do

  get "numbers" => "numbers#index"
  post "numbers_generate_list" => "numbers#generate_list"
  get "numbers_show" => "numbers#show"
  root "numbers#index"

end

app/models/number.rb
class Number < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  include NumbersHelper

  def index
    Number.delete_all
  end

  def generate_list
    number = params[:list_number][:number].to_i
    Generate_List.generate number
    per_page_value params[:list_number][:per_page]
    redirect_to numbers_show_path
  end

  def show
    list = Number.all
    per_page = session[:per_page]
    list = WillPaginate::Collection.create(2, per_page, list.length)do |pager|
      pager.replace list
    end
    @display_list = list.paginate(page: params[:page], per_page: per_page)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper

  def per_page_value value
    if value != ''
      session[:per_page] = value
    else
      session[:per_page] = 5
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NumberList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/numbers/index.html.erb
<%= form_for(:list_number, url: numbers_generate_list_path) do |f| %>
<%= f.label "Number:" %>
<%= f.text_field :number, id:'Number' %>
<%= f.label "Number per Page:" %>
<%= f.text_field :per_page, id:'number_per_page' %>
<%= f.submit "Generate List" %>
<% end %>

app/views/numbers/show.html.erb
<%= will_paginate @display_list %>
<% @display_list.each do |num| %>
<%= num.name %> </br>
<% end %>
<%= will_paginate @display_list %>